# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87df239be24512d5bf83be239322362405067291c68e6f2024e1d7a781cf8ffe7ce6923a11aae9ba392fa6187738e36b9792f035371457b3d562e2b0f21f775d
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://75e372d3.ngrok.io
  user_name: EahLocksmithTest216.mailer@gmail.com
  password: security349
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A3-7WGyQvexSAEBrh2HsKlh5BnXp
  password: 7ELVC5BERKUZABMF
  login:  akrowdeesummitcounty_api1.gmail.com

test:
  secret_key_base: f7977df8030d1c52c2846410a116e01cb3369bb0d6650ecef49c4cc9577da5abbdb11f808680a8f3c0594d75421d28c05663297fb5b0db863a62983b1824548e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: https://launchschool.com/
